### ISSUE TITLE
Can't connect to Team City

### ISSUE THREAD

**Issue by LegendORC** [AutomatedArchitecture/SirenOfShame#126]
Please provide as much info from below as possible:

### Steps to reproduce

1. Downloaded and Install Siren of Shame from http://sirenofshame.com/Downloads
2. Clicked on Configure Server(s)
3. CI Server > Selected as Team City
4. Entered URL, Username and Password from my CI server
5. Clicked Connect button
6. I got message

```
Error connecting to server: The underlying connection was closed: An unexpected error occurred on a send.
Unable to read data from the transport connection: An existing connection was fourcibly closed by the remote host.
```

### Expected behavior

My CI Server should be connected

### Actual behavior

Can't connect to my CI Server

### Configuration

**Sos Version:** 

2.4.13

**Build Server:** 
- [ ] AppVeryor
- [ ] Bamboo
- [ ] CruiseControl.Net
- [ ] Jenkins/Hudson
- [x] Team City
- [ ] TFS 2015+
- [ ] TFS 2010-2013 (xaml build definition)
- [ ] Travis

**Any Relevant Logs**

See [screenshot](http://blog.sirenofshame.com/2012/01/how-to-report-errors.html) for how to retrieve

2019-11-26 15:59:53,413 [1] ERROR TeamCityServices.ServerConfiguration.ConfigureTeamCity [(null)] - Error connecting to server
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TeamCityServices.TeamCityService.<GetProjects>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TeamCityServices.ServerConfiguration.ConfigureTeamCity.<<ReloadProjects>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TeamCityServices.ServerConfiguration.ConfigureTeamCity.<ReloadProjects>d__10.MoveNext()
2019-11-26 15:59:55,131 [1] DEBUG SirenOfShame.ViewBuilds [(null)] - Removing child controls because: anyBuildNameChanged = False; numberOfBuildsChanged: False

**Comment by lprichar** [comment]
Sounds like a network issue.  By any chance can you run Fiddler to watch the network traffic?  You should be seeing a request to `[yourserver]/httpAuth/app/rest/projects`.  If you aren't able to watch with Fiddler can you please try navigating to `[yourserver]/httpAuth/app/rest/projects` in a browser?  It should prompt for network credentials and then list all projects.

**Comment by LegendORC** [comment]
> /httpAuth/app/rest/projects

Hi @lprichar 

I try to brown via the browser with https://ci.xxxxx.com/httpAuth/app/rest/projects and here is the result :

```
<projects count="10" href="/httpAuth/app/rest/projects">
<project id="_Root" name="<Root project>" description="Contains all other projects" href="/httpAuth/app/rest/projects/id:_Root" webUrl="https://ci.xxxxx.com/project.html?projectId=_Root"/>
<project id="Ams" name="AMS" parentProjectId="_Root" href="/httpAuth/app/rest/projects/id:Ams" webUrl="https://ci.xxxxx.com/project.html?projectId=Ams"/>
<project id="AmsMobile" name="AMS-MOBILE" parentProjectId="_Root" href="/httpAuth/app/rest/projects/id:AmsMobile" webUrl="https://ci.xxxxx.com/project.html?projectId=AmsMobile"/>
<project id="AcsReactApp" name="ACS-REACT-APP" parentProjectId="_Root" href="/httpAuth/app/rest/projects/id:AcsReactApp" webUrl="https://ci.xxxxx.com/project.html?projectId=AcsReactApp"/>
<project id="Specflow" name="AMS-SPECFLOW" parentProjectId="_Root" href="/httpAuth/app/rest/projects/id:Specflow" webUrl="https://ci.xxxxx.com/project.html?projectId=Specflow"/>
<project id="ams_spec" name="SPEC" parentProjectId="Specflow" href="/httpAuth/app/rest/projects/id:ams_spec" webUrl="https://ci.xxxxx.com/project.html?projectId=ams_spec"/>
<project id="ConfMobile" name="CONF-MOBILE" parentProjectId="_Root" href="/httpAuth/app/rest/projects/id:ConfMobile" webUrl="https://ci.xxxxx.com/project.html?projectId=ConfMobile"/>
<project id="Htfn" name="HTFN" parentProjectId="_Root" href="/httpAuth/app/rest/projects/id:Htfn" webUrl="https://ci.xxxxx.com/project.html?projectId=Htfn"/>
<project id="MobileApi" name="Mobile API" parentProjectId="_Root" description="This project use for blue print API testing." href="/httpAuth/app/rest/projects/id:MobileApi" webUrl="https://ci.xxxxx.com/project.html?projectId=MobileApi"/>
<project id="Vanilla_Orchard" name="Vanilla Orchard" parentProjectId="_Root" description="Vanilla Orchard" href="/httpAuth/app/rest/projects/id:Vanilla_Orchard" webUrl="https://ci.xxxxx.com/project.html?projectId=Vanilla_Orchard"/>
</projects>
```

It look like i can connect to TeamCity API 🤔
