### ISSUE TITLE
Team City Issue -   id of 'username' but one didn't exist

### ISSUE THREAD

**Issue by pkatarii** [AutomatedArchitecture/SirenOfShame#144]
Please provide as much info from below as possible:

### Steps to reproduce

1. SoS connects to TC
2. Discover and Select Builds to Monitor
3. SoS Displays selected builds

### Expected behavior

Build Monitors refreshes

### Actual behavior

yellow warning: Expected an element with an id of 'username' but one didn't exist. Is TeamCity down?

### Configuration

**Sos Version:** 
  2.4.13

Team city version .. TeamCity Professional 2020.2.4 (build 86063)

[From the 'What's Going On?' button]

**Build Server:** 
- [ ] AppVeryor
- [ ] Bamboo
- [ ] CruiseControl.Net
- [ ] Jenkins/Hudson
- [x ] Team City
- [ ] TFS 2015+
- [ ] TFS 2010-2013 (xaml build definition)
- [ ] Travis

**Any Relevant Logs**

2021-05-11 07:50:05,686 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - OperatingSystem: Microsoft Windows NT 6.2.9200.0
2021-05-11 07:50:05,686 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - DotNetVersion: 4.0.30319.42000
2021-05-11 07:50:05,686 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - SosVersion: 2.4.13
2021-05-11 07:50:05,686 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - SoftwareInstanceId: 
2021-05-11 07:50:05,686 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - DeviceConnected: True
2021-05-11 07:50:05,687 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - FirmwareVersion: 102
2021-05-11 07:50:05,687 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - HardwareVersion: 1
2021-05-11 07:50:05,687 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - HardwareType: Standard
2021-05-11 07:50:05,687 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - ErrorDate: 11/05/2021 7:50:05 AM
2021-05-11 07:50:05,688 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - ErrorMessage: Expected an element with an id of 'username' but one didn't exist. Is TeamCity down?
2021-05-11 07:50:05,688 [1] INFO  SirenOfShame.Lib.ExceptionMessageBox [(null)] - StackTrace: SirenOfShame.Lib.Exceptions.ServerUnavailableException: Expected an element with an id of 'username' but one didn't exist. Is TeamCity down?
   at TeamCityServices.TeamCityService.SetCookie(String rootUrl, String userName, String password)
   at TeamCityServices.TeamCityService.GetBuildsStatuses(String rootUrl, String userName, String password, IEnumerable`1 watchedBuildDefinitions)
   at TeamCityServices.Watcher.TeamCityWatcher.GetBuildStatus()
   at SirenOfShame.Lib.Watcher.WatcherBase.GetBuildStatusAndFireEvents()

See [screenshot](http://blog.sirenofshame.com/2012/01/how-to-report-errors.html) for how to retrieve

**Comment by lprichar** [comment]
Confirmed.  Sorry for the delay.  Looking into this now.  Hope to get a fix shortly.

**Comment by lprichar** [comment]
@pkatarii Do you mind confirming if the PR above fixes the issue for you?

**Comment by pkatarii** [comment]
@lprichar started to have a look but ran into a few issues .. will get back to you tomorrow

**Comment by pkatarii** [comment]
@lprichar Yep, confirmed that fixed the issue, thanks
