### ISSUE TITLE
Can not add a CruiseControl xml feed to SoS

### ISSUE THREAD

**Issue by dsmorse** [AutomatedArchitecture/SirenOfShame#61]
I have CruiseControl xml feeds from both Jenkins and GoCD... I can not add either to SoS.

With the feed from GoCD I get this error: 
Error connecting to server: Reference to undeclared entity 'nbsp' line 94, postion 51

With the feed from Jenkins I get this error:
Error connecting to server: An exceptions during the operation, making the result invalid. Check InnerException for exception details

As a point of reference, I can connected to the same jenkins server if I select Jenkins/Hudson from the CI server type list.

**Comment by dsmorse** [comment]
Here is the snipped from the logs:
2015-09-10 22:15:48,540 [1] ERROR CruiseControlNetServices.CruiseControlNetService [(null)] - Error connecting to server
System.Xml.XmlException: Reference to undeclared entity 'nbsp'. Line 94, position 51.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at CruiseControlNetServices.CruiseControlNetService.<>c__DisplayClass3.<GetProjects>b__1(Object s, DownloadStringCompletedEventArgs e)
2015-09-10 22:15:48,548 [1] ERROR CruiseControlNetServices.ServerConfiguration.ConfigureCruiseControlNet [(null)] - System.Xml.XmlException: Reference to undeclared entity 'nbsp'. Line 94, position 51.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at CruiseControlNetServices.CruiseControlNetService.<>c__DisplayClass3.<GetProjects>b__1(Object s, DownloadStringCompletedEventArgs e)
2015-09-10 22:15:49,068 [CiWatcher] DEBUG SirenOfShame.Lib.Watcher.RulesEngine [(null)] - InvokeRefreshStatus: Some build status changed
